#ifndef LINKARCH_CONFIG
#define LINKARCH_CONFIG



/* Kernel config */

// Module config
#define LINKARCH_MODULE_MAX_NAME_LENGTH 16

// Mode config
#define LINKARCH_MODE_MAX_NAME_LENGTH 16

// Mode Transiction config
#define LINKARCH_MODE_TRANSITION_MAX_NAME_LENGTH 16

// Controller config

#define LINKARCH_CONTROLLER_NUMBER_OF_MODULES 5
#define LINKARCH_CONTROLLER_NUMBER_OF_MODES 1
#define LINKARCH_CONTROLLER_NUMBER_OF_MODETRANSITIONS 1

#define LINKARCH_CONTROLLER_TASK_STACK_SIZE 1024
#define LINKARCH_CONTROLLER_TASK_PRIORITY 5

#define LINKARCH_DEBUG_MODE 1
#define LINKARCH_CONTROLLERTASKCORE 0


/* Platform mcu config */

// Sim Actuator config
#define LINKARCH_SIM_ACTUATOR_LINKARCHSOCKET_PATH "/tmp/linkarchSocket"
#define LINKARCH_SIM_ACTUATOR_LINKSERVERSOCKET_PATH "/tmp/linkhubSocket"

#define LINKARCH_SIM_ACTUATOR_HANDSHAKE_MESSAGE "LINKARCH"
#define LINKARCH_SIM_ACTUATOR_HANDSHAKE_MESSAGE_SIZE 8




#endif  // LINKARCH_CONFIG
